# Generated by Django 5.1.1 on 2024-09-16 01:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='duracao',
            field=models.TimeField(help_text='Ex: 2 horas e 30 minutos', verbose_name='Duração'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='palestrantes',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL, verbose_name='Palestrante'),
        ),
    ]
