# Generated by Django 5.1 on 2024-08-29 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='is_ativo',
            field=models.BooleanField(default=False, editable=False, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='conta',
            name='is_funcionario',
            field=models.BooleanField(default=False, editable=False, verbose_name='Funcionario?'),
        ),
        migrations.AddField(
            model_name='conta',
            name='nome_completo',
            field=models.CharField(default='None', max_length=40, verbose_name='Nome Completo'),
        ),
        migrations.CreateModel(
            name='AlunoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(choices=[('BCC', 'Ciencia da Computação'), ('AG', 'Agronomia'), ('QI', 'Quimica Industrial'), ('ZO', 'Zootecnia')], max_length=3, verbose_name='Curso')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(choices=[('CS', 'Ciência da Computação'), ('SE', 'Engenharia de Software'), ('AI', 'Inteligência Artificial'), ('DS', 'Data Science'), ('AG', 'Agronomia'), ('AP', 'Agropecuária'), ('AS', 'Agroecologia'), ('AGRO', 'Engenharia Agronômica'), ('ZO', 'Zootecnia'), ('VM', 'Medicina Veterinária'), ('ZOA', 'Produção Animal'), ('ZOA', 'Nutrição Animal'), ('QI', 'Química Industrial'), ('EQ', 'Engenharia Química'), ('CQ', 'Química'), ('MT', 'Materiais e Metalurgia')], max_length=4, verbose_name='Formação')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
