# Generated by Django 5.1 on 2024-08-30 20:06

import stdimage.models
import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_conta_is_ativo_conta_is_funcionario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alunomodel',
            options={'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterModelOptions(
            name='conta',
            options={'verbose_name': 'Conta', 'verbose_name_plural': 'Contas'},
        ),
        migrations.AlterModelOptions(
            name='professormodel',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
        migrations.AddField(
            model_name='alunomodel',
            name='img',
            field=stdimage.models.StdImageField(default='static/images/default_user.webp', force_min_size=False, upload_to=usuarios.models.get_file_path, variations={'thumb': {'crop': True, 'height': 460, 'width': 460}}, verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='alunomodel',
            name='turno',
            field=models.CharField(choices=[('horario_integral', 'Horario Integral'), ('noturno', 'Noturno')], default='#', max_length=18, verbose_name='Turno'),
        ),
        migrations.AddField(
            model_name='professormodel',
            name='img',
            field=stdimage.models.StdImageField(default='static/images/default_user.webp', force_min_size=False, upload_to=usuarios.models.get_file_path, variations={'thumb': {'crop': True, 'height': 460, 'width': 460}}, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='nome_completo',
            field=models.CharField(default='', max_length=40, verbose_name='Nome Completo'),
        ),
    ]
