# Generated by Django 5.1 on 2024-08-30 20:19

import stdimage.models
import usuarios.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_alunomodel_options_alter_conta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunomodel',
            name='img',
            field=stdimage.models.StdImageField(default='default/default_user.webp', force_min_size=False, upload_to=usuarios.models.get_file_path, variations={'thumb': {'crop': True, 'height': 460, 'width': 460}}, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='professormodel',
            name='img',
            field=stdimage.models.StdImageField(default='default/default_user.webp', force_min_size=False, upload_to=usuarios.models.get_file_path, variations={'thumb': {'crop': True, 'height': 460, 'width': 460}}, verbose_name='Imagem'),
        ),
    ]
