# Generated by Django 5.1 on 2024-08-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_alunomodel_img_alter_professormodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='nome_completo',
            field=models.CharField(max_length=40, verbose_name='Nome Completo'),
        ),
    ]
