# Generated by Django 3.2.8 on 2024-09-09 04:53

from django.db import migrations
import stdimage.models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_alunomodel_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunomodel',
            name='img',
            field=stdimage.models.StdImageField(default='default/default_user.avif', force_min_size=False, upload_to=usuarios.models.get_file_path, variations={'thumb': {'crop': True, 'height': 360, 'width': 360}}, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='professormodel',
            name='img',
            field=stdimage.models.StdImageField(default='default/default_user.avif', force_min_size=False, upload_to=usuarios.models.get_file_path, variations={'thumb': {'crop': True, 'height': 360, 'width': 360}}, verbose_name='Imagem'),
        ),
    ]
